version: "3"
services:
    mongo_db:
        image: "mongo"
        ports:
          - "27017:27017"

    posters_app:
        build: .
        depends_on:
            - mongo_db
        ports:
            - "5001:5001"